#!/bin/sh

. ./dashrand

mktemp() {
  local t=tmp. x d=/tmp cmd=': >$d/$t$x'

  while :; do
    case $1
    in -d) cmd='mkdir $d/$t$x'
    ;; -f) cmd='mkfifo $d/$t$x'
    ;; -p) shift
           d=$1
    ;; -*) return 1
    ;; '') break
    ;; *)  t=$1           
    esac
    shift || break
  done

  readrand x
  while ! (set -C; umask 0077; eval $cmd 2>/dev/null); do
    readrand x
  done

  echo $d/$t$x
}
    
