#!/bin/sh

if ! type return_val >/dev/null 2>&1; then
  alias return_val='echo'
fi

gsub() {
  case "$2"
  in *[!*]*) :
  ;; *)
    return_val "$1"
    return
  esac

  local h= v=$1
  while :; do
    case "$v"
    in *$2*)
      eval "h=\"$h\${v%%$2*}$3\""
      eval "v=\"\${v#*$2}\""
    ;; *)
      return_val "$h$v"
      break
    esac
  done
}

sub() {
  case "$2"
  in *[!*]*) :
  ;; *)
    return_val "$1"
    return
  esac

  case "$1"
  in *$2*) eval "echo \"\${1%%$2*}$3\${1#*$2}\""
  ;; *)    return_val "$1"
  esac
}
