#!/bin/sh

if [ "$(echo /.*)" = '*' ]; then
  alias restore_fopt='set -f'
else
  alias restore_fopt='set +f'
fi

alias for_line='set -f; _OFS=$IFS; IFS=
; for'
alias do_line='do IFS=$_OFS; restore_fopt;'

