#!/bin/sh

eval _SEED=\${_SEED:-$$}

readrand() {
  _SEED=$((_SEED * 256 % 32768 +
           ( _SEED / 16384 + _SEED / 8192 ) % 2 * 128 +
           ( _SEED / 8192  + _SEED / 4096 ) % 2 * 64  +
           ( _SEED / 4096  + _SEED / 2048 ) % 2 * 32  +
           ( _SEED / 2048  + _SEED / 1024 ) % 2 * 16  +
           ( _SEED / 1024  + _SEED / 512  ) % 2 * 8   +
           ( _SEED / 512   + _SEED / 256  ) % 2 * 4   +
           ( _SEED / 256   + _SEED / 128  ) % 2 * 2   +
           ( _SEED / 128   + _SEED / 64   ) % 2 ))
  eval $1=$_SEED
}

